### ISSUE TITLE
Need help to find the logic that prevents routing before login

### ISSUE THREAD

**Issue by akhi-bamhore** [jualoppaz/single-spa-layout-app#29]
I would like to know how and where the logic written that checks if token is available in session and based on token it decides which app or which route to load.

**Comment by akhi-bamhore** [comment]
@jualoppaz please help me understand this

**Comment by jualoppaz** [comment]
Hi @akhi-bamhore ,

the code you are looking for that check if token is available is here: https://github.com/jualoppaz/single-spa-layout-app/blob/f117dd1382defaaaa0a678dabad4ef8136085434/src/App.vue#L22-L24

In the other hand, the code that manages what microfronted is visible in any time is the root-application.js, which is located in the hosting app: 

https://github.com/jualoppaz/single-spa-login-example-with-npm-packages/blob/master/root-application.js

Hope be helpful 😄
